:source-highlighter: prettify
:icons: font
:toc-title:
:toc: left

= Blue4IT Groovy Workshop
Frank van Westerop <https://github.com/fvanwesterop[@fvanwesterop]>; Gijs Mollema <https://github.com/gmollema[@gmollema]>
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

[.text-right]
https://fvanwesterop.github.io/blue4it-groovy-workshop/[Home] | https://github.com/fvanwesterop/blue4it-groovy-workshop.git[Repo] | http://docs.oracle.com/javase/8/docs/api/[JDK 8] | http://www.groovy-lang.org/gdk.html[GDK 2.4.7] | http://www.groovy-lang.org/api.html[API 2.4.7]

== 2. Fun with Groovy and Scripting

== 2.1 Running Groovy

Je kunt op verschillende manieren met Groovy aan de slag, afhankelijk van of je snel even iets wil proberen, een script wil schrijven of een compleet project wil beginnen. We zullen er hier kort een paar proberen.

=== 2.2 Groovy vanaf de CommandLine

==== 2.2.1 De Groovy Shell
Heb je een machine waarop Groovy geïnstalleerd is, dan is ook de Groovy Shell bechikbaar. Je start deze met het commando `groovysh`. Persoonlijk vind ik dit geen prettig ding om te gebruiken: Hij is voor Groovy begrippen minder intuitief. Maar pak je de http://docs.groovy-lang.org/docs/next/html/documentation/tools-groovysh.html[documentatie] erbij dan kom je er wel uit. Het is een nuttige tool om snel wat uit te proberen door de korte feedback loop die je hebt in zo'n shell en hij is altijd beschikbaar als Groovy zelf beschikbaar is. Maar er zijn handigere tools dus in deze workshop gebruiken we `groovysh` verder niet.

==== 2.2.2 Groovy Shebang

Wanneer je een shell script bekijkt van een POSIX systeem (UNIX, Linux, OSX etc.) dan zie je dat deze altijd begint met de zogenaaamde shebang line, meestal `\#!/bin/bash` of `#!/bin/sh`. Die shebang line vertelt je shell (bash, zsh) welke interpreter deze moet gebruiken om je script uit te voeren. Maar in principe kun je hier iedere executable aangeven. Op deze manier kun je bijvoorbeeld een Ruby, Python of Groovy script als shell script gebruiken. Maar omdat dit soort interpreters niet op ieder systeem op dezelfde plek geinstalleerd worden, is het verstandig om de `env` utiity te gebruiken om het volledige pad naar je script interpreter te resolven. Bijvoorbeeld: `#!\usr\bin\env groovy`.

