:source-highlighter: prettify
:icons: font
:toc-title:
:toc: left
:sourcedir: resources

= Blue4IT Groovy Workshop
Frank van Westerop <https://github.com/fvanwesterop[@fvanwesterop]>; Gijs Mollema <https://github.com/gmollema[@gmollema]>
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

[.text-right]
https://fvanwesterop.github.io/blue4it-groovy-workshop/[Home] | https://github.com/fvanwesterop/blue4it-groovy-workshop.git[Repo] | http://docs.oracle.com/javase/8/docs/api/[JDK 8] | http://www.groovy-lang.org/gdk.html[GDK 2.4.7] | http://www.groovy-lang.org/api.html[API 2.4.7]

== 3. Groovy Programer in 4 Minutes


=== 3.1 Lab-01: TrailCalendar
Je gaat een simpel evenementen calendertje met cross-lopen, genaamd Trail Calendar maken. Je begint met een Java programmaatje en bouwt dat om naar Groovy.

==== 3.1.1 De Java Versie

Ga naar de root van je workshop directory om te beginnen:

[[app-listing]]
[source,bash]
----
$ cd <workshop_home>

$ git checkout lab-01
$ cd workspace/lab-01/trailcalendar
$ gradle init
----
Vervang de inhoud van de file `build.gradle` met de volgende inhoud:
[[app-listing]]
[source,groovy]
.file: 'build.gradle'
----
include::{sourcedir}/labs/lab-01/build.gradle[]
----
Bouw en run het project met Gradle:
[[app-listing]]
[source,bash]
----
$ gradle run
----
Je zou nu een werkende Java versie van het programma moeten hebben. Op de console zie je dan output van twee evenementen. Bekijk de sources in Sublime.

==== 3.1.2 Een Eerste Groovy Versie
Probeer de main class `MainJ` te runnen vanuit Sublime met Groovy (sneltoets `Ctr-B` of `Cmd-B`). Dit werkt niet omdat het een Java file is. Dat gaan we oplossen.

Navigeer in je shell naar de root van `lab01` en doe het volgende:
[[app-listing]]
[source,language]
----
# Maak een groovy sources folder aan
mkdir -p trailcalendar/src/main/groovy

# Kopieer alle Java sources naar de Groovy folder
cp -r trailcalendar/src/main/java/* trailcalendar/src/main/groovy

# Hernoem alle Java sources en package in de Groovy Folder
cd trailcalendar/src/main/groovy
mv j g
mv MainJ.java MainG.groovy
cd g
mv TrailCalendar.java TrailCalendar.groovy
mv TrailEvent.java TrailEvent.groovy
----

Pas de build file `build.gradle` aan:

* De main-class heet nu `MainG`
* Voeg de Groovy library toe: `compile 'org.codehaus.groovy:groovy-all:2.4.7'`

Open de file `MainG.groovy` in Sublime en pas de classname en imports aan:
[[app-listing]]
[source,groovy]
----
import g.TrailCalendar;
import g.TrailEvent;

(...)

class MainG {

(...)

----

Open ook de files `TrailEvent.groovy` en `TrailCalendar.groovy` in Sublime en pas de package names aan.

Ga nu weer naar je shell, build en run met Gradle: `gradle run`. Als de boel bouwt en draaid: Gefeliciteerd! Je kunt nu 'Groovy Programmer' aan je CV toevoegen!

==== 3.1.3 Groovy-nize...

Ok, je hebt nu in feite een Java programma wat je als script kunt draaien. Ga maar naar de MainG class in Sublime en draai de app vauit Sublime. Je kunt wijzigingen aanbrengen en direct het resultaat zien zonder eerst te compileren; een volledige (Gradle) build is niet perse nodig. Je kunt zelfs een shebang line toevoegen in `MainG.groovy` en draaien als shell script.

Op zich mooi, maar het is in feite gewoon Java code. Je krijgt instructies 'how to make Java more Groovy...'

=== 3.2 Lab-02: TrailCalendar REST Service

==== 3.2.1 De REST Service

Ga naar de root van je workshop directory en checkout lab-02:

[[app-listing]]
[source,bash]
----
$ cd <workshop_home>

$ git checkout lab-02
$ cd workspace/lab-02/trailcalendar
----

Open de file `src/main/groovy/trailcalendar-rest-service.groovy` in Sublime en start de service, of navigeer naar `src/main/groovy` en start de service vanuit de shell met `groovyclient` of het `groovy` commando. Starten met `gradle run` werkt ook, maar het stoppen werkt dan minder goed.

Ga naar http://localhost:4000/trailcalendar/findAll/[http://localhost:4000/trailcalendar/findAll/] en naar http://localhost:4000/trailcalendar/find/1[http://localhost:4000/trailcalendar/find/<id>] om de JSON output te bekijken.

Open de andere sources in Sublime en bekijk hoe de service zo'n beetje werkt. Bekijk vervolgens `CalendarServlet`. De finder methods gebruiken een closure om de events op te halen.

Pas de finders aan zodat de wrappers rond de event objectjes gestripped worden.

==== 3.2.2 De REST Client
